config/routes.rb
Rails.application.routes.draw do

  get 'states/youwonstates' => 'states#youwonstates', as: :youwonstates

  resources :states

  get 'cities/youwon' => 'cities#youwon', as: :youwon

  resources :cities

 

end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
    @states = State.all
  end

  def youwonstates
    @states = State.all 
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    #we're going to be tailoring a message in the case of a wrong or duplicate answer:

@message = ""

 

#your standard new instance of the Resource line:

@state = State.new(state_params)

 

#we'll need this to check if the answer is a duplicate:

@states = State.all

 

#let's make sure the answer is correct, and that it's not a duplicate.

#see the Application Helper for these methods:

correct = check_answer_state(@state.name)

is_dup = check_for_dup_state(@state.name,@states)

 

#we're going to have a couple messages for when the user enters something that is not a city, or is a duplicate answer

if correct == false

@message = "That is not a state TTS is in."

elsif is_dup == true

@message = "You already guessed that one!"

end

 

respond_to do |format|

#if we have > 1 city left to name, and the user's answer is true and not a duplicate answer, we'll save it in the database and redirect back to the same page

if @states.count <= 48 && correct == true && is_dup == false && @state.save

format.html { redirect_to new_state_path, notice: 'State was successfully created.' }

format.json { render action: 'show', status: :created, location: @state }

#if this is our last city to name, and the user's answer is true and not a duplicate answer, we'll save it in the database and redirect to the 'you won!' page

elsif @states.count == 49 && correct == true && is_dup == false && @state.save

format.html { redirect_to youwonstate_path, notice: 'State was successfully created.' }

format.json { render action: 'show', status: :created, location: @state }

else

format.html { render action: 'new' }

format.json { render json: @state.errors, status: :unprocessable_entity }

end

end

end
  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>

<% if @state.errors.any? %>

<div id="error_explanation">

<h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

 

<ul>

<% @state.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

<% end %>

<!-- No real changes to the field below, just added a line of direction to the user 'Enter a state:' -->

<div class="field">

Enter a state: <br />

<%= f.label :name %><br>

<%= f.text_field :name, :autofocus => true %>

<!-- :autofocus => true puts the cursor on that particular field when the page is loaded -->

</div>

<div class="actions">

<%= f.submit %>

</div>

<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<!--

We will use this page (and corresponding _form page)

as the page where the User enters their guesses.

Notice the @message from the controller!

This will display if the user makes

an incorrect or duplicate guess.

Below the form, we will have their correct answers

displayed - numbered so they can see how many they've

answered so far.

-->

 

<h1>Name the States Where TTS Has a Campus</h1>

 

<div>

<%= @message %>

</div>

<br />

 

<%= render 'form' %>

 

<% @states.each do |state| %>

<%= "#{state.id}. #{state.name}" %><br />

<% end %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>

app/views/states/youwonstates.html.erb
<!--

User will reach this page if they

name all states correctly

-->

<h1>You did it!</h1>

<h3>You named all states where TTS has a Campus!</h3>

 

<p>Here they are:</p>

 

<div>

<% @states.each do |state| %>

<%= "#{state.id}. #{state.name}" %><br />

<% end %>

</div>