config/routes.rb
Rails.application.routes.draw do

  get 'states/youwonstates' => 'states#youwonstates', as: :youwonstates

  resources :states

  get 'cities/youwon' => 'cities#youwon', as: :youwon

  resources :cities

 

end

app/models/city.rb
class City < ActiveRecord::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

include ApplicationHelper

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
    @cities = City.all
  end

  def youwon
    @cities = City.all
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    #we're going to be tailoring a message in the case of a wrong or duplicate answer:

  @message = ""

   

  #your standard new instance of the Resource line:

  @city = City.new(city_params)

   

  #we'll need this to check if the answer is a duplicate:

  @cities = City.all


  #let's make sure the answer is correct, and that it's not a duplicate.

  #see the Application Helper for these methods:

  correct = check_answer(@city.name)

  is_dup = check_for_dup(@city.name,@cities)

   

  #we're going to have a couple messages for when the user enters something that is not a city, or is a duplicate answer

  if correct == false

  @message = "That is not a city TTS is in."

  elsif is_dup == true

  @message = "You already guessed that one!"

  end

   

  respond_to do |format|

  #if we have > 1 city left to name, and the user's answer is true and not a duplicate answer, we'll save it in the database and redirect back to the same page

  if @cities.count <= 2 && correct == true && is_dup == false && @city.save

  format.html { redirect_to new_city_path, notice: 'City was successfully created.' }

  format.json { render action: 'show', status: :created, location: @city }

  #if this is our last city to name, and the user's answer is true and not a duplicate answer, we'll save it in the database and redirect to the 'you won!' page

  elsif @cities.count == 3 && correct == true && is_dup == false && @city.save

  format.html { redirect_to youwon_path, notice: 'City was successfully created.' }

  format.json { render action: 'show', status: :created, location: @city }

  else

  format.html { render action: 'new' }

  format.json { render json: @city.errors, status: :unprocessable_entity }

  end

  end

  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>

<% if @city.errors.any? %>

<div id="error_explanation">

<h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

 

<ul>

<% @city.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

<% end %>

<!-- No real changes to the field below, just added a line of direction to the user 'Enter a city:' -->

<div class="field">

Enter a city: <br />

<%= f.label :name %><br>

<%= f.text_field :name, :autofocus => true %>

<!-- :autofocus => true puts the cursor on that particular field when the page is loaded -->

</div>

<div class="actions">

<%= f.submit %>

</div>

<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<!--

We will use this page (and corresponding _form page)

as the page where the User enters their guesses.

Notice the @message from the controller!

This will display if the user makes

an incorrect or duplicate guess.

Below the form, we will have their correct answers

displayed - numbered so they can see how many they've

answered so far.

-->

 

<h1>Name the Cities Where TTS Has a Campus</h1>

 

<div>

<%= @message %>

</div>

<br />

 

<%= render 'form' %>

 

<% @cities.each do |city| %>

<%= "#{city.id}. #{city.name}" %><br />

<% end %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/cities/youwon.html.erb
<!--

User will reach this page if they

name all cities correctly

-->

<h1>You did it!</h1>

<h3>You named all cities where TTS has a Campus!</h3>

 

<p>Here they are:</p>

 

<div>

<% @cities.each do |city| %>

<%= "#{city.id}. #{city.name}" %><br />

<% end %>

</div>

app/views/cities/youwonstates.html.erb
<!--

User will reach this page if they

name all states correctly

-->

<h1>You did it!</h1>

<h3>You named all states where TTS has a Campus!</h3>

 

<p>Here they are:</p>

 

<div>

<% @states.each do |state| %>

<%= "#{state.id}. #{state.name}" %><br />

<% end %>

</div>